import { useState } from 'react'
import { HEALTH_DISCLAIMER } from '../healthDisclaimer.js'
import { SourcesSheet } from './shared/SourcesLink.jsx'
import { HEALTH_GOALS, topicsForGoals } from '../data/healthGoals.js'

export default function DisclaimerPopup({ onAgree }) {
  const [showSources, setShowSources] = useState(false)
  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" aria-labelledby="disclaimer-title">
      <div className="modal-sheet">
        <div className="modal-handle" />
        <div className="modal-icon">⚕️</div>
        <h2 className="modal-title" id="disclaimer-title">Important Health Notice</h2>

        <div className="modal-body">
          <p><strong>{HEALTH_DISCLAIMER}</strong></p>
          <p>
            Old2New is a recipe transformation tool. We are not doctors, dietitians, or medical professionals, and recipes and nutrition figures are generated by AI. Calorie and macro values are per-serving estimates, not measurements.
          </p>
          <p>
            If you are taking a GLP-1 medication (such as Ozempic, Wegovy, or Mounjaro), have diabetes, food allergies, or any other medical condition, follow the advice of your healthcare team first.
          </p>
          <p>
            By using Old2New you agree that:
          </p>
          <p>
            • This is <strong>not medical advice</strong><br />
            • You will consult your doctor first<br />
            • You use this app at your own discretion
          </p>
          <p>
            <button type="button" onClick={() => setShowSources(true)} style={{ background: 'none', border: 'none', padding: 0, color: 'var(--green-dark)', fontWeight: 700, textDecoration: 'underline', cursor: 'pointer', fontFamily: 'var(--font)', fontSize: 14 }}>
              📚 View the sources behind our nutrition information
            </button>
          </p>
        </div>

        <button className="btn btn-primary" onClick={onAgree}>
          I Understand and Agree
        </button>
      </div>
      {showSources && (
        <SourcesSheet
          title="Sources & References"
          topics={topicsForGoals(HEALTH_GOALS.map(g => g.id))}
          showMethodology
          onClose={() => setShowSources(false)}
        />
      )}
    </div>
  )
}
