// The one disclaimer text used everywhere (first-run notice, About, References,
// every Sources sheet, the paywall and the PDF cookbook). Keep it identical.
export const HEALTH_DISCLAIMER =
  'Old2New provides general food and nutrition information for educational purposes only. ' +
  'It is not intended to diagnose, treat, cure, or prevent any disease or medical condition. ' +
  'Nutrition values may be estimates and individual dietary needs vary. ' +
  'Consult a physician, registered dietitian, or other qualified healthcare professional ' +
  'before making dietary changes related to a medical condition or medication.'

export const SHORT_DISCLAIMER =
  'Old2New is for informational purposes only. Not medical advice. Consult your physician before changing your diet.'

// How Old2New's nutrition numbers are produced. Shown wherever calories or
// macros appear (Macros tab sheet, References page, PDF cookbook).
export const NUTRITION_METHODOLOGY = [
  'Calories, protein, carbohydrates, fat and fiber shown by Old2New are estimates, not laboratory measurements.',
  'They are generated by the AI model that writes the recipe, based on the typical nutrient composition of each ingredient as published in reference data such as the USDA FoodData Central database, and on the amounts in the recipe.',
  'Values are expressed per serving, using the number of servings stated in the recipe, and are rounded to whole calories and whole grams.',
  'The estimates do not account for brand-to-brand differences, exact portion sizes, cooking losses or gains (for example water or fat absorbed or lost), or substitutions you make yourself.',
  '"Before" values describe a typical version of the original dish and "after" values the transformed recipe; the comparison is an estimate of direction and rough size, not an exact difference.',
  'If you need accurate nutrition information for a medical reason, use a verified nutrition database or a registered dietitian and check the Nutrition Facts label on each product you use.',
]
